### ISSUE TITLE
Use well-known URIs.

### ISSUE THREAD

**Issue by cpaasch** [network-quality/draft-ietf-ippm-responsiveness#17]
Feedback from Jana Iyengar.

**Comment by LPardue** [comment]
I'd like to discuss some more what is in scope here. Placing a config file under a /.well-known seems reasonable. But requiring the test endpoints to be available there too seems problematic. For example, the config JSON format allows for a full URL including query parameters, that's useful for some types of deployment.

**Comment by cpaasch** [comment]
Fixed with https://github.com/network-quality/draft-ietf-ippm-responsiveness/pull/72
