### ISSUE TITLE
Clarify definition of probe and RTT aggregation methodology (section 4.2) 

### ISSUE THREAD

**Issue by hawkinsw** [network-quality/draft-ietf-ippm-responsiveness#38]
In Section 4.2, "probe" is used without precise definition. In order to make it more clear what is being measured, it would be helpful if it is clear that a probe encompasses multiple RTTs (i.e., a probe encompasses 

1. The time it takes a new connection between client and server to do a DNS handshake, a TCP handshake, TLS handshake, and 1-byte HTTP GET.
2. The time it takes to do a 1-byte HTTP GET on a load-generating connection).

In addition, the technique for aggregating these different RTTs in a final value could be more clear in Section 4.2, too. 

I am happy to suggest wording, if you think it would help!

Thanks!
Will

**Comment by hawkinsw** [comment]
See my comment https://github.com/network-quality/goresponsiveness/issues/10#issuecomment-1076893392 -- I think that I explain my confusion better in that issue than I do here.

**Comment by cpaasch** [comment]
See my comment at https://github.com/network-quality/draft-ietf-ippm-responsiveness/issues/37#issuecomment-1166069504

I am thinking of changing the probing to continuous probes on existing connections. Allows for a much higher sample-size, thus more stable results. It comes at the cost of eliminating the TCP/TLS/... stages. But, that can be ok (?).

**Comment by cpaasch** [comment]
Tried to clarify with af69ae22ea917a7afd5ade9a2b6d1948d63ac558. Please reopen if that's not sufficient.
