### ISSUE TITLE
Consider putting server-side config in appendix

### ISSUE THREAD

**Issue by cpaasch** [network-quality/draft-ietf-ippm-responsiveness#39]
Feedback from Bjorn Mork:

We can put server-side configs in the appendix, similar to https://datatracker.ietf.org/doc/html/rfc8806

**Comment by moeller0** [comment]
I wonder whether the spec could at least recommend that the servers use NTP to aim for reliabke clocks? This would potentially allow to dissect the RTT into two OWDs, which would helpa lot with figuring out how an RPM result might come about.

**Comment by LPardue** [comment]
Using NTP for this purpose doesn't seem like a practical deployment option for many HTTP-based purposes. Determining OWD is a hard problem, we shouldn't try and solve that in this spec IMO.

**Comment by moeller0** [comment]
I am not convinced that most servers are not already using "proper" time synchronization (and this is where NTP comes in, the idea is not to turn RPM into a back channel for NTP updates/queries). And for the RPM purpose it seems sufficient to have a stable clock output so that changes in OWDs as a function of load can be measured and interpreted. But it is much easier to sanity check if RPM servers would just use a well defined timestamp, instead of reinventing the wheel... 

I agree OWDs can be arbitrarily hard, but for the use case at hand to see how OWDs change under load it is acceptable if the base OWDs are not 100% precise.

**Comment by LPardue** [comment]
How would you calculate the OWD?

**Comment by moeller0** [comment]
Well, the sender takes a timestamp when it transmits and receices the small payload request, and calculates OWD estimates intuitively:
forward OWD: Server time - transmit time
return OWD: receive time - Server time

If server and client are sufficiently synchronised and use the same time base OWD estimates are likely good enough. If not it is still possible to first calculate the resting state OWD baselines without saturation and compare these with the OWDs measured under saturating load.

As timebase I would simply use UTC and be done with, as format I would use one of NTP's no need to reinvent the wheel ;)

**Comment by LPardue** [comment]
Sure anything is feasible, I just don't think we should invent an HTTP-based OWD measuring procedure as part of this spec.

**Comment by moeller0** [comment]
Yes, hence the idea of just having RPM servers package a well defined timestamp in the latency probe packet, which clients can process or ignore. Getting this added now to the spec and implementation  will be much easier then after RPM servers are already deployed... and while the goal seems to be a single numer as result, people will be interested in whichvdirection their link sucks more. The draft seems to propose to tackle this by saturating both directions sequentially, but surely OWDs could help with that effort.

**Comment by LPardue** [comment]
There's no probe packet, it's HTTP request and response., which might be arbitrarily packetized.

If you need a unique value per HTTP response, then that defeats static content or caching, which some might want to use.

**Comment by LPardue** [comment]
> On second reading, this sounds impolite, sorry that was not my intent.

No problem, no offence taken. We should take the discussion to a different issue to continue it. I'm not against doing something but mandating any specific server timestamp in a response will constrain practical HTTP deployments, potentially limiting deployment scenarios. If the OWD measure is useful, then putting that under a different probe type (request path, or something else) seems a like a possible option

**Comment by cpaasch** [comment]
Added a server-side config in the Appendix. @randall  - please feel free to extend/fix/whatnot :-)
