### ISSUE TITLE
Explain what different things an app can do when saturation is not reached within the time-limit

### ISSUE THREAD

**Issue by cpaasch** [network-quality/draft-ietf-ippm-responsiveness#40]
Feedback from Bjorn Mork:

> Re-reading this, I realize that I went out to harsh here. Sorry.
> 
> I think it can be improved by replacing things like
> 
> "It is left to the implementation what to do when saturation is not
> reached within that time-frame."
> 
> with a precise description of what to do.

There are two approaches here:

Either, the implementation aborts and errors out.
Or, the implementation nevertheless measures the responsiveness and either presents the result as a valid result or as a result with a low confidence score.

We can probably outline the options that an implementation has.

**Comment by moeller0** [comment]
I would vote for also implementing an optional mode which needs to be explicitly requested on the command line that instructs the test to keep trying or alternatively allowing to request a minimal saturation period (which the server could be free to reject, preferably by telling how long a test would be acceptable).

I appreciate the 20 seconds goal, but IMHO this clearly needs to be secondary to actually getting interpretable results, no?
