### ISSUE TITLE
DNS client behaviour is under-defined

### ISSUE THREAD

**Issue by LPardue** [network-quality/draft-ietf-ippm-responsiveness#43]
The spec says something along the lines of 

> The test measures the time needed to make a DNS request

that timing is going to be subject to things such as whether it's plain Do53, DoT, DoH, DoQ, etc etc. Whether caching is in effect, other DNS things I'm no expert in.

I think it would help to expand more on these points in the spec, otherwise you're subject to client implementation defaults or people with little understanding of these things not knowing what to do.

**Comment by cpaasch** [comment]
Agree'd. I would tend to remove DNS timing out of the spec. There are too many variables with DNS.

**Comment by hawkinsw** [comment]
> Agree'd. I would tend to remove DNS timing out of the spec. There are too many variables with DNS.

I want to make a strong +1 to this sentiment.

**Comment by cpaasch** [comment]
Same comment as in https://github.com/network-quality/draft-ietf-ippm-responsiveness/issues/37#issuecomment-1166069504

What do you think if we just reuse connections for the timing probes. That allows for far more probes and a more stable result. Meaning, it would eliminate DNS entirely as well.

Any strong opinions?

**Comment by cpaasch** [comment]
Removing DNS.
