### ISSUE TITLE
"1-byte response" -=> Capture some considerations about Header Section sizes

### ISSUE THREAD

**Issue by LPardue** [network-quality/draft-ietf-ippm-responsiveness#47]
The probe requests are for 1 byte of message content.

An HTTP header section is a complete list of header fields in an HTTP message. In HTTP/2 we need a mandatory `:status` pseudo-header field, and most servers will add a bunch of other response headers like `Date`, `Server` etc. All of these stand a chance at dwarfing your response size. HPACK (or QPACK) is likely to affect the on-wire size of these messages. QPACK could even cause the content to be blocked.

All of these things can interfere with the timing of the HTTP response that we are trying to measure. And they stand to have a lot of variation. I think the specification would do well to add considerations related to header sections, fields and compression.

**Comment by cpaasch** [comment]
#64 adds the "SHOULD" that servers should be terse with the headers.

**Comment by LPardue** [comment]
commented on the commit, I think the phrase terse is too terse :-)

We're talking about HTTP here, lets just be transparent with HTTP folks about what is good bad or ugly. Terms like "terse" are subjective and don't really help - because they provide no rationale about why that's a good thing to do (that a server operator might choose to ignore on purpose).

**Comment by cpaasch** [comment]
@randall  - can you take a look at this?

**Comment by cpaasch** [comment]
Randall was quick!
