### ISSUE TITLE
The meaning of a negative change in throughput is underspecified

### ISSUE THREAD

**Issue by hawkinsw** [network-quality/draft-ietf-ippm-responsiveness#52]
https://github.com/network-quality/draft-ietf-ippm-responsiveness/blob/38f2b241d6f96588488a89c864d023bfa0432075/draft-ietf-ippm-responsiveness.txt#L405

The specification says what do to if/when the current throughput moving average is 5% more than the previous throughput moving average, but does not define the meaning/behavior if the difference between the current and the previous moving throughput average is negative. I see this type of behavior often and it would be good to specify the meaning.

**Comment by cpaasch** [comment]
Good point - we can be more explicit about it. Unless you have other ideas, I suggest to treat a negative change in throughput the same way we treat a less than 5% increase.

**Comment by cpaasch** [comment]
I wrote:

```
    - If the moving average aggregate goodput at interval i is more than a 5% increase over
      the moving average aggregate goodput at interval i - 1, the network has not yet reached full link utilization.
      Continue for 4 more iterations.
    - If the responsiveness at interval i is more than a 5% reduction over the responsiveness at interval i - 1, the network
      has not yet reached full buffer occupancy.
      Continue for 4 more iterations.
```

Also, I think it's better to remove the text describing what the stability is. In the end, the above lines should make things clear.
