### ISSUE TITLE
Specify how a *server* can signal HTTP2 vs HTTP (with our without encryption)

### ISSUE THREAD

**Issue by hawkinsw** [network-quality/draft-ietf-ippm-responsiveness#66]
Given that we are interested in making it possible for low-power devices to accurately calculate an RPM without taxing their CPUs doing unnecessary encryption *and* the new piece of the specification describing how to attribute confidence, I think that we might need to specify how a server can communicate what it supports to a client. 

I discussed with Jeroen something I thought might work:

A low-power client can always "power down" what the server supports: a server supports HTTP2 (with SSL)? Okay, the client can use that or it can choose to do a CPU-efficient HTTP test (knowing full well the confidence will be lower). 

A low-power server can always "power down" what the client supports: the client will only go as "high" as what the server supports.

The answer might be as simple as advertising `https` vs `http` but I thought I would write down this issue regardless.

**Comment by hawkinsw** [comment]
Great question and you are exactly correct! However, my student researcher and I are assessing how these measurements fare when calculated on embedded devices (either servers or clients) and the protocol is not able to saturate the connection because they are CPU-bound doing the crypto methods.

If a provider ever wanted to deploy RPM servers or clients on their CPE then not being able to calculate reasonable metrics because the devices are CPU-bound could be a problem.

Do you agree or disagree?

**Comment by LPardue** [comment]
I agree that any bottleneck independent of the network under test, will affect the test. This is presently the case when trying to, for example, load test an HTTP server the is heavily optimized with clients that not equally scaled.

The constraints on CPE are real, and as much as we might wish it can happen, its unlikely they can make changes to be an infinite source or sink that is unbottlenecked. 

However, I don't think its fair to the actual Internet protocols that are used by the majority of traffic to conflate them with RPM metrics of little used protocols. We see this type ofbthing already when folks do iperf tests and get one figure, then complain when a transport protocol doesnt achieve exactly the same.

Maybe thus cones down to the interpretation of what confidence means. Maybe more honest labels would help avoid conflation - plaintext HTTP can be called an INSECURE AND SYNTHETIC testing profile and much caution must be applied when drawing any conclusions or predixtions about how representative encrypted protocols could behave.

**Comment by cpaasch** [comment]
We discussed the HTTP vs HTTPS vs HTTP3 story with Stuart in the context of bonjour discovery.

We think that the best way for bonjour discovery is to announce the protocol (HTTP, HTTPS or HTTP3) via bonjour, embedded in the service name.

For public measurement endpoints (outside of local discovery) the differentiation between HTTP and HTTPS will happen through the json-config URL.

Not sure how we can work H3 here though. Could be part of HTTPS ALT-SVC ? Or an option in the json-config.

**Comment by cpaasch** [comment]
PR #72 and #74 should take care of this.

The DNS service announcement will say whether or not this is UDP (QUIC) or TCP (HTTPS) for the config-fetch. The config then itself will either provide and http or an https URL. If the config-fetch was on QUIC the HTTPS-URL should support QUIC.
