### ISSUE TITLE
'moving average stability' definition permits increasing speeds

### ISSUE THREAD

**Issue by skbenj** [network-quality/draft-ietf-ippm-responsiveness#69]
It seems that the draft as it stands has a definition for "moving average stability" that allows the speed to be increasing but still count as stable.

> o  moving average stability during the period between intervals b and
> e: Whether or not, for all b<=x<e, the absolute difference is less
> than 5% between the moving average aggregate goodput at interval x
> and the moving average aggregate goodput at interval x+1.  If all
> absolute differences are below 5% then the moving average has
> achieved stability.  If any of the absolute differences are 5% or
> more then the moving average has not achieved stability.

Consider a connection where the moving average goodput increases by 4.9% every interval:
```
>>> seq = [1.0]
>>> for _ in range(4):
...     seq.append(seq[-1] * 1.049)
... 
>>> seq
[1.0, 1.049, 1.100401, 1.154320649, 1.210882360801]
```

> If a) there have been load-generating connections added in
> the past four intervals and b) there has been moving average
> stability during the period between intervals i-4 and i,
> then the network has reached full link utilization and the
> algorithm terminates.

If the moving average goodput follows the above pattern (being 1.2108... at interval i, 1.1543... at interval i-1 etc), then there has been "moving average stability" even though the goodput has increased by 21% since the period i-4.

Is this expected?

**Comment by cpaasch** [comment]
Hello, thanks for the feedback!

Yes, this is indeed what would happen.

The question is:
1. Which kind of environment would show such kind of a pattern of the increase of "moving average goodput" ?
2. Do you have a better suggestion for detecting stability? We are open to having a better answer :-)

**Comment by cpaasch** [comment]
We are entirely reworking the stability detection. Instead of 5% increase, we are now looking for a standard deviation of the instantaneous measurements during the last 4 periods to converge towards less than 5%.

Experiments have shown that this works very well.
