### ISSUE TITLE
Ambiguities in latest draft (spec v3)

### ISSUE THREAD

**Issue by hawkinsw** [network-quality/draft-ietf-ippm-responsiveness#70]
There are several things I am confused about -- sorry! I am going to send some questions here and then I am going to attempt to make some changes to the draft via PR so that you can give some feedback that way. 

https://github.com/network-quality/draft-ietf-ippm-responsiveness/blob/123f98c023cf91f8253c6198969f4c94ddfcbcba/draft-ietf-ippm-responsiveness.md?plain=1#L459

Probes are being launched two different intervals (see below for my related question). As I understand the algorithm (again, see below), there are 

1. probes launched every 100ms (the type of this probe is unspecified, but I assume that it is the self probe on the first LGC -- again, see below) Or, (again, see below), are we launching both self *and* foreign probes every 100ms? (See below for a consolidating idea that may make things "better")
2. probes launched every 1 second (again, the type of this probe is unspecified, but I assume that it is a foreign probe?)

https://github.com/network-quality/draft-ietf-ippm-responsiveness/blob/123f98c023cf91f8253c6198969f4c94ddfcbcba/draft-ietf-ippm-responsiveness.md?plain=1#L515

Is this self probing on the LGC established in the previous step? Or foreign probes? We need to specify.

https://github.com/network-quality/draft-ietf-ippm-responsiveness/blob/123f98c023cf91f8253c6198969f4c94ddfcbcba/draft-ietf-ippm-responsiveness.md?plain=1#L520

`responsiveness` here is undefined -- which of the probe metrics are considered when calculating? Is there a moving average? 

https://github.com/network-quality/draft-ietf-ippm-responsiveness/blob/123f98c023cf91f8253c6198969f4c94ddfcbcba/draft-ietf-ippm-responsiveness.md?plain=1#L523

Does this mean that we do not do any of these per-interval "stability" checks for the next four intervals and simply update our statistics at each interval?

https://github.com/network-quality/draft-ietf-ippm-responsiveness/blob/123f98c023cf91f8253c6198969f4c94ddfcbcba/draft-ietf-ippm-responsiveness.md?plain=1#L524

By `reduction` do we mean, "responsiveness" decreased? As in, responsiveness went from, say, 55ms to 70ms? It would be hard to rationalize adding more streams and having the latency decrease, but seeing the word decrease here makes me question my thought. 

https://github.com/network-quality/draft-ietf-ippm-responsiveness/blob/123f98c023cf91f8253c6198969f4c94ddfcbcba/draft-ietf-ippm-responsiveness.md?plain=1#L526

See above.

**Comment by cpaasch** [comment]
Line 428, we need to speak out that we probe on the first load-generating connection and always probe on that one. And repeat it again at line 515.

> responsiveness here is undefined -- which of the probe metrics are considered when calculating? Is there a moving average?

Need to reference the section "Aggregating the measurements".

"Calculate the RPM as the weighted mean" -> "Calculate the responsiveness as the weighted mean". - in general clean up use of RPM (which is a unit) vs Responsiveness (which is the value itself)

Let's also rephrase the "stability" detection to make it a computation of standard deviation with the algorithm accepting a certain threshold after X periods. So, there are 2 inputs to the algorithm: the percentage threshold and X.

We need to note in the text that depending on the behavior of the network and the chosen inputs things may not converge.

Also, need to put a limit to the total number of connections. Something reasonable is necessary.

**Comment by cpaasch** [comment]
> Line 428, we need to speak out that we probe on the first load-generating connection and always probe on that one. And repeat it again at line 515.

I tried to clarify this:
"Given this information, we recommend that at each responsiveness probing round, we send no more than 6 probes on different load-generating connections (choosing randomly among the available load-generating connections)"

> > responsiveness here is undefined -- which of the probe metrics are considered when calculating? Is there a moving average?
> Need to reference the section "Aggregating the measurements".

I think it's clearer now.

> "Calculate the RPM as the weighted mean" -> "Calculate the responsiveness as the weighted mean". - in general clean up use of RPM (which is a unit) vs Responsiveness (which is the value itself)

Done!

> Let's also rephrase the "stability" detection to make it a computation of standard deviation with the algorithm accepting a certain threshold after X periods. So, there are 2 inputs to the algorithm: the percentage threshold and X.

Reworked this quite a bit!

> We need to note in the text that depending on the behavior of the network and the chosen inputs things may not converge.

I think that is taken care of.

> Also, need to put a limit to the total number of connections. Something reasonable is necessary.

Done. 16 is the magic number.
