### ISSUE TITLE
How to Order Measurements

### ISSUE THREAD

**Issue by hawkinsw** [network-quality/draft-ietf-ippm-responsiveness#71]
@Schickendantzj Made a great point in a meeting that he and I had earlier today: When we are considering "the last *x* measurements", should that be "the last *x* measurements completed" or "the last *x* measurements started"? If the latter, what should we do about measurements that have not yet completed?

**Comment by cpaasch** [comment]
That is indeed a great point!

IMO it should be the last x measurements completed. There is nothing we can do about those that take a lot of time. And indeed, when there is *a lot* of bufferbloat, it can taked a long time.

**Comment by cpaasch** [comment]
Clarifying this in the next update:

"measurements considers the last 4 seconds worth of completed responsiveness probes."
