### ISSUE TITLE
Add me to teamrpm slack workspace

### ISSUE THREAD

**Issue by gabekassel** [network-quality/draft-ietf-ippm-responsiveness#73]
I heard there's a slack workspace related to this work/community. Could you please add me (`kassel01@gmail.com`) when time permits?

Thanks

**Comment by hawkinsw** [comment]
Done!

**Comment by hawkinsw** [comment]
Complete!

**Comment by hawkinsw** [comment]
@cpaasch Feel free to close this issue! We added @gabekassel to the Slack!
