### ISSUE TITLE
draft-ietf-ippm-responsiveness.md minor nits

### ISSUE THREAD

**Issue by gregbo** [network-quality/draft-ietf-ippm-responsiveness#80]
--- draft-ietf-ippm-responsiveness.md	2023-06-02 21:22:26
+++ draft-ietf-ippm-responsiveness.md+	2023-06-02 21:25:27
@@ -861,10 +861,10 @@
 # Acknowledgments
 
 Special thanks go to Jeroen Schickendantz for his tireless
-enthousiasm around the project and his contributions to this I-D and the development
+enthusiasm around the project and his contributions to this I-D and the development
 of the Go responsiveness measurement tool.
 We would also like to thank Rich Brown for his editorial pass over this I-D.
-We also thank Erik Auerswald, Matt Matthis and Omer Shapira for their constructive feedback on the I-D.
+We also thank Erik Auerswald, Matt Mathis and Omer Shapira for their constructive feedback on the I-D.
 
 --- back

**Comment by hawkinsw** [comment]
Thank you!! We will fix immediately!

**Comment by gregbo** [comment]
I caught one more.  All references to draft-ietf-tcpm-rfc793bis can be replaced with RFC9293 now.

**Comment by cpaasch** [comment]
Done!
